[tool.pyright]

reportMissingImports = "Warning"
reportMissingTypeStubs = true
reportGeneralTypeIssues = true
reportOptionalMemberAccess = true
reportOptionalSubscript = true

pythonVersion = "3.11"
pythonPlatform = "Windows"

extraPaths = [
    "..",
]

[tool.bpytest]
test_mode="runtime"
pythonpath=""
module_list=""
display_output=true
toggle_console=true
raise_error=false
blender_exe="C:/Program Files/Blender Foundation/Blender 4.0/blender.exe"


