[tool.pyright]

reportMissingImports = "Warning"
reportMissingTypeStubs = true
reportGeneralTypeIssues = true
reportOptionalMemberAccess = true
reportOptionalSubscript = true

pythonVersion = "3.11"
pythonPlatform = "Windows"

[tool.bpytest]
test_search_relative_path=""
test_mode="background"
selected_functions=[]
pythonpath=""
module_list=""
display_output=true
toggle_console=true
raise_error=false


