from .collector import Collector as Collector, collect_conftest_files as collect_conftest_files
from .entity import BColors as BColors, BpyTestConfig as BpyTestConfig, CollectorString as CollectorString, SessionInfo as SessionInfo, TestUnit as TestUnit
from .fixtures import Scope as Scope, fixture_manager as fixture_manager
from .print_helper import print_failed as print_failed, print_header as print_header
from .runner import TestRunner as TestRunner
from .types import ExitCode as ExitCode

class TestManager:
    def __init__(self, bpytest_config: BpyTestConfig, session_info: SessionInfo, collector: Collector) -> None: ...
    @property
    def bpytest_config(self) -> BpyTestConfig: ...
    @property
    def failed(self) -> int: ...
    @property
    def success(self) -> int: ...
    @property
    def total_time(self) -> float: ...
    def execute(self) -> ExitCode: ...
