from .entity import BColors as BColors, TestUnit as TestUnit

def print_header(text: str, color: BColors = ..., bold: bool = True): ...
def print_failed(test_list: list[TestUnit]): ...
def print_selected_functions(total_collected_tests: int, total_deselected_tests: int, total_selected_tests: int): ...
